/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ndtx.ecommercedemo.api;

import java.util.List;

import org.springframework.http.ResponseEntity;

import com.ndtx.ecommercedemo.model.Getproducts200Response;



public interface ProductsApi {

	ResponseEntity<List<Getproducts200Response>> getAllProducts(Long productId, Long brandId, String startDate);

}
